---
title: "tp_multi-omics"
author: "Lynda"
date: "20/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Lecture des fichier:
```{r}
miRNA <- read.csv(file = "mirna.csv", header = T, sep ="," ,row.names = 1)
dim(miRNA)
```
1/ miRNA: on a  150 échantillons , 184 variables

```{r}
mRNA <- read.csv(file = "mrna.csv", header = T, sep =",", row.names = 1 )
dim(mRNA)

```
2/ mRNA: on a  150 échantillons , 200 variables


```{r}
prot <- read.csv(file = "protein.csv", header = T, sep =",", row.names = 1 )
dim(prot)

```
3/ prot: on a  150 échantillons , 142 variables

```{r}
sampl_group <- read.csv(file = "sample_group.csv", header = T, sep ="," ,row.names = 1)
dim(sampl_group)

```
4/ sampl_group : on a  150 échantillons , 1 variable

```{r}

# Focntion qui calcul le coefficient de variation
  # Parametre un vecteur qui correspond à une colone donée.
  # Return une valeur int ou float

coef_var <- function(vect){
  
  return (mean(vect) / sd(vect))
}

coef_var(mRNA[,1])
```


